# .github/workflows/App-Run.yml

name: App-Run

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: '18 2 * * *'
jobs:
  run:
    if: always()  
    runs-on: ${{ matrix.os }}
    timeout-minutes: 359
    environment: production
    continue-on-error: ${{ matrix.allow-failure || true}}
    strategy:
      matrix:
        python-version: [3.7,3.8,3.9]
        os: [ubuntu-18.04,ubuntu-latest]
      fail-fast: false 
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  
    - name: Build docker
      run: |
        docker build .
    - name: Upload release asset
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./*.jar
        tag: jar
        file_glob: true
        overwrite: true
        release_name: jar      
    - name: Update
      run: |
        rm README.md
        date >> README.md         
        python generate.py        
    - name: Commit  ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add .
        git commit -am "Update File"
        git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3        
